plugins {
    id 'net.fabricmc.fabric-loom' version "${fabric_loom_version}"
}

sourceSets {
    main {
        java.srcDir file('../common/src/main/java')
        resources.srcDir file('../common/src/main/resources')
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
}

processResources {
    inputs.property 'version', project.version

    filesMatching('fabric.mod.json') {
        expand version: project.version
    }
}
