plugins {
	id 'base'
}

allprojects {
	group = rootProject.maven_group
	version = rootProject.mod_version
}

subprojects {
	base {
		archivesName = rootProject.archives_name
	}

	tasks.matching { it.name in ['jar', 'sourcesJar', 'remapJar', 'remapSourcesJar'] }.configureEach {
		archiveFileName = it.name.toLowerCase().contains('sources')
			? "${rootProject.archives_name}-${project.version}-${project.name}-sources.jar"
			: "${rootProject.archives_name}-${project.version}-${project.name}.jar"
	}

	plugins.withId('java') {
		java {
			toolchain.languageVersion = JavaLanguageVersion.of(rootProject.java_version as int)
			withSourcesJar()
		}
	}

	tasks.withType(JavaCompile).configureEach {
		it.options.release = rootProject.java_version as int
	}
}

tasks.named('build') {
	dependsOn ':fabric:build', ':forge:build', ':neoforge:build'
}
