# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Mod Properties
mod_version = 1.9.0
maven_group = me.lucaslah
archives_name = no-report-button
mod_id = noreportbutton
mod_name = No Report Button
mod_license = LGPL-3.0-or-later
mod_authors = Lucaslah
mod_description = Removes the chat report button from the game menu screen

# Minecraft Properties
minecraft_version=26.3
java_version=25

# Dependencies
fabric_loader_version=0.19.5
fabric_loom_version=1.15-SNAPSHOT
fabric_api_version=0.161.0+26.3
forge_gradle_version=[7.0.17,8)
forge_version=26.3-66.0.9
moddevgradle_version=2.0.148
neoforge_version=26.3.0.40-beta