# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Mod Properties
mod_version = 1.7.1
maven_group = me.lucaslah
archives_name = no-report-button
mod_id = noreportbutton
mod_name = No Report Button
mod_license = LGPL-3.0-or-later
mod_authors = Lucaslah
mod_description = Removes the chat report button from the game menu screen

# Minecraft Properties
minecraft_version=26.1
java_version=25

# Dependencies
fabric_loader_version=0.18.5
fabric_loom_version=1.15-SNAPSHOT
fabric_api_version=0.144.4+26.1
forge_gradle_version=[7.0.17,8)
forge_version=26.1-62.0.9
moddevgradle_version=2.0.141
neoforge_version=26.1.0.17-beta