plugins {
    id 'java'
    id 'net.minecraftforge.gradle' version "${forge_gradle_version}"
}

sourceSets {
    main {
        java.srcDir file('../common/src/main/java')
        resources.srcDir file('../common/src/main/resources')
    }
}

minecraft {
    runs {
        configureEach {
            workingDir = layout.projectDirectory.dir('run')
            systemProperty 'eventbus.api.strictRuntimeChecks', 'true'
        }

        register('client')

        register('server') {
            args '--nogui'
        }
    }
}

repositories {
    minecraft.mavenizer(it)
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    mavenCentral()
}

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${forge_version}")
}

processResources {
    def sharedIcon = file('../common/src/main/resources/assets/noreportbutton/icon.png')

    inputs.properties([
            version          : project.version,
            forge_version    : forge_version,
            minecraft_version: minecraft_version,
            mod_description  : mod_description,
            mod_name         : mod_name,
            mod_license      : mod_license,
            mod_authors      : mod_authors,
            mod_id           : mod_id,
            shared_icon      : sharedIcon.path
    ])

    from(sharedIcon) {
        into ''
        rename { 'icon.png' }
    }

    filesMatching("META-INF/mods.toml") {
        expand(
                version: project.version,
                forge_version: forge_version,
                minecraft_version: minecraft_version,
                mod_description: mod_description,
                mod_name: mod_name,
                mod_license: mod_license,
                mod_authors: mod_authors,
                mod_id: mod_id
        )
    }
}

jar {
    manifest {
        attributes(
                'Implementation-Version': project.version,
                'MixinConfigs': 'noreportbutton.mixins.json'
        )
    }
}
