plugins {
    id 'java'
    id 'net.neoforged.moddev' version "${moddevgradle_version}"
}

sourceSets {
    main {
        java.srcDir file('../common/src/main/java')
        resources.srcDir file('../common/src/main/resources')
    }
}

neoForge {
    version = neoforge_version

    runs {
        client {
            client()
        }
        server {
            server()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
}

processResources {
    inputs.properties([
            version: project.version,
            minecraft_version: minecraft_version,
            neoforge_version: neoforge_version,
            mod_description: mod_description,
            mod_name: mod_name,
            mod_license: mod_license,
            mod_authors: mod_authors,
            mod_id: mod_id
    ])

    filesMatching('META-INF/neoforge.mods.toml') {
        expand(
                version: project.version,
                minecraft_version: minecraft_version,
                neoforge_version: neoforge_version,
                mod_description: mod_description,
                mod_name: mod_name,
                mod_license: mod_license,
                mod_authors: mod_authors,
                mod_id: mod_id
        )
    }
}

jar {
    manifest {
        attributes 'Implementation-Version': project.version
    }
}
